author: Jimmy Wang

keywords: 
  - OI
  - c++
  - python
  - IT

description: 蒟蒻wjr————一个爱好用c++和python coding的蒟蒻

# 导航栏头部名称
nav_name: 蒟蒻wjr

# 导航栏座右铭
motto: "不遭人妒是庸才"

github: "https://github.com/wangjunrui666/"

# 站点图标和APP图标
favicon: 
  icon: /images/favicon.ico
  touch_icon: /images/touch-icon.png

# RSS文件位置
rss: 

# 自定义样式文件
custom_styles: 

# 自定义脚本文件
custom_scripts: 

# 代码高亮主题: normal | night | night blue | night bright | night eighties
highlight_theme: "night eighties"

# 开启数学公式渲染
mathjax: true

copyright:
  enable: true
  author: "蒟蒻wjr"
  show_link: true
  more: '版权声明: 本博客所有文章除特别声明外, 均采用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a> 许可协议. 转载请注明出处!'

# 建站时间. 格式：YYYY-MM-DD
start_time: "2019-6-2"

# 如何开启 评论&统计 插件：https://godbmw.com/passages/2018-11-15-theme-bmw-docs-zh/
# 请申请自己的 appid 和 appkey，并且替换下面的 appid 和 appkey
leancloud:
  appid: Hyq9wkH495DgNHWhDQCOfQSp-gzGzoHsz # 填写您的appid
  appkey: WaR7nrzhliHj9aVwdQzkdlGd # 填写您的appkey
  comment: false # 是否开启评论系统
  count: false # 是否开启文章统计

# 需要保证leancloud.count为true
welcome: 
  enable: false
  interval: 30

# 需要保证leancloud.comment为false
disqus: 
  enable: false
  id: 

# 需要保证leancloud.count为false
busuanzi: false

# 存放sha256加密的密码
# 拥有所有加锁文章的阅读权限
passwords: 
  - 9e539189f68103867e8b5ed336e027e23c447bddcd53284ad8d1d2be30c39f7f # godbmw

share:
  twitter: true
  facebook: true
  weibo: true
  qq: true
  wechat: true

analytics:
  baidu:
    enable: true
  google:
    enable: true
    id: 
  "360":
    enable: true
    id: 

# 打赏图片
#reward:
#    src: /images/wechat.png
#    alt: "WeChat"
#  -
#    src: /images/alipay.png
#    alt: "AliPay"

# 第三方库的CDN地址
# 请根据情况自行决定是否替换为国内CDN
cdn: 
  leancloud: "//cdn.jsdelivr.net/npm/leancloud-storage@3.11.1/dist/av-min.js"
  mathjax: "//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"
  valine: "//unpkg.com/valine/dist/Valine.min.js"
  busuanzi: "//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"
  font_awesome: "//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"

nav:
  -
    name: "首页"
    path: "/"
  -
    name: "归档"
    path: "/archives/"
  -
    name: "标签"
    path: "/tags/"
  -
    name: "分类"
    path: "/categories/"
  -
    name: "友链"
    path: "/friends/"
  -
    name: "关于"
    path: "/about/"
  -
    name: "2048"
    path: "/2048/"

footer:
  - 
    title: "博客推荐"
    children:
      - 
        name: "CTJ's Blog - 一个Coding爱好者的博客"
        path: "https://ctj12461.netlify.com"
  -
    title: "抓到我"
    children: 
      -
        name: "洛谷"
        path: "https://www.luogu.com.cn/space/show?uid=133322"
      -
        name: "LOJ"
        path: "https://loj.ac/user/9929"
      -
        name: "代码库"
        path: "https://github.com/wangjunrui666/wangjunrui-s-code"
  

footer_contact: "Email: 2189535056@qq.com"

friends_avatar_cdn: 
friends:
  -
    nickname: CTJ's Blog - 一个Coding爱好者的博客 # 友链名称
    avatar: /images/friends/ctj12461.netlify.com.jpg # 友链头像
    site: https://ctj12461.netlify.com # 友链地址
    meta: 博主机房同学 # 友链介绍
    show: true # 是否展示此友链
